//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::chat::Entity as Chat;
pub use super::message::Entity as Message;
pub use super::update::Entity as Update;
pub use super::user::Entity as User;
